name: Push Frontend and Backend image to Docker HUb

on:
  push:
    branches:
      - 'main'

env:
  EKS_CLUSTER_NAME: team1-eks-cluster
  AWS_REGION: eu-central-1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
            file: ./ui/Dockerfile
            push: true
            tags: |
              saurabhd2106/frontend:latest
              saurabhd2106/frontent:1.0.0  

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
            context: ./api
            push: true
            tags: |
              saurabhd2106/backend:latest
              saurabhd2106/backend:1.0.0  
      
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION
    
      - name: Deploy to EKS
        run: |
            kubectl apply -f ./namespace.yml
            kubectl apply -f ./db_deploy.yml
            kubectl apply -f ./db_clusterip.yml
            kubectl apply -f ./backend_deploy.yml
            kubectl apply -f ./loadbalancer_backend.yml
            kubectl apply -f ./frontend_deploy.yml
            kubectl apply -f ./loadbalancer_frontend.yml
    
