name: Push Frontend and Backend image to Docker HUb

on:
  push:

env:
  EKS_CLUSTER_NAME: team1-eks-cluster
  AWS_REGION: eu-central-1
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOSTNAME: ${{secrets.SSH_HOST}}
  USER_NAME: ${{secrets.USER_NAME}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
            file: ./ui/Dockerfile
            push: true
            tags: |
              saurabhd2106/frontend:latest
              saurabhd2106/frontent:1.0.0  

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
            file: ./api/Dockerfile
            push: true
            tags: |
              saurabhd2106/backend:latest
              saurabhd2106/backend:1.0.0
    
      - name: Deploy application
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            
            
                cd /home/ubuntu/<PROJECT_DIRECTORY> &&
                git checkout dev &&
                git fetch --all &&
                git reset --hard origin/dev &&
                git pull origin dev &&
                sudo docker compose up -d