name: Push Frontend and Backend image to Docker HUb

on:
  push:

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOSTNAME: ${{secrets.SSH_HOST}}
  USER_NAME: ${{secrets.USER_NAME}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:    
      - name: Deploy application
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            
                git checkout dev &&
                git fetch --all &&
                git reset --hard origin/dev &&
                git pull origin dev &&
                cd /home/ubuntu/3_tier_app_solution_k8s &&
                sudo docker compose up -d
                '