name: Push Frontend and Backend image to Docker HUb

on:
  push:
    branches:
      - 'dev'

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOSTNAME: ${{secrets.SSH_HOST}}
  USER_NAME: ${{secrets.USER_NAME}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
      - name: Deploy application
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

                rm -rf 3_tier_app_solution_k8s &&
                git clone https://github.com/saurabhd2106/3_tier_app_solution_k8s.git &&
                cd 3_tier_app_solution_k8s &&
                sudo docker compose up -d
                '